name: flowers_client_app
description: A new Flutter project.

dependencies:
  camera:
  path_provider: ^0.4.1
  http:
  flutter:
    sdk: flutter
  charts_flutter:
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true

flutter_icons:
  android: true 
  ios: true
  image_path: "flower.png"